### ISSUE TITLE
liveview component that replicate the nav of scaffold-eth

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai-shang-projects#12]
money:  `1500R`
<img width="520" alt="image" src="https://user-images.githubusercontent.com/12784118/166206416-8c2cc276-e736-4d41-8bfd-ecdcd0a869c0.png">

**Comment by kenspirit** [comment]
- Meatamsk 登录
- 余额实施显示
- 地址显示
- 网络切换
