### ISSUE TITLE
Escript to update Gist.

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai-shang-projects#13]
money: `500R`

check the doc here:

> https://docs.github.com/en/rest/gists/gists#update-a-gist

if any API key, using it as a env variable.

an example need to update:

> https://gist.github.com/leeduckgo/4c8b6504b7eb23c8ca75cb3a705eb17b

**Comment by yangcancai** [comment]
Give it to me !

**Comment by leeduckgo** [comment]
> Give it to me !

Good!
