### ISSUE TITLE
an liveview component & demo for multi move chain login.

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai-shang-projects#18]
Money: `$300`

including Petron, Martain and starmask.

**Comment by zven21** [comment]
🙋🏻‍♀️

**Comment by zven21** [comment]
Demo it's here: https://github.com/myastrallabs/aptos_wallet

**Comment by leeduckgo** [comment]
https://stcscan.io/main/transactions/detail/0xfef886ccc58252a1bfbec4b9d927db9479358891e1b51aaa5f172ebd91c41a99
