### ISSUE TITLE
Msg Signers for ethereum / aptos

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai-shang-projects#22]
Money: `200 U`/per proj.
Details: 
* ethereum-signer based on scaffold-eth
* aptos-signer based on scaffold-move
* signature msg get by `param` in url, such as: `http://localhost:3000/msg=hello`
* output the msg and signature in the screen

**Comment by v1xingyue** [comment]
* ethereum-signer 

运行如图: 
![image](https://user-images.githubusercontent.com/974169/212352167-1552f262-c04c-43d9-99c0-4f089aa85500.png)



项目地址:  https://github.com/v1xingyue/eth-signer
其他提示： 如果 mac 下运行，建议修改 package.json 去掉 --openssl-legacy-provider 选项，否则 可能运行不起来。 

* aptos-signer 

运行效果如图: 
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/974169/212527037-23c48ccd-f1ed-43ce-929f-e40fa6bfb686.png">


项目地址: https://github.com/v1xingyue/aptos-signer

**Comment by baidang201** [comment]
认领第三个
signature msg get by param in url, such as: http://localhost:3000/msg=hello
下周一提交，如果提交不了，大家可以继续。

**Comment by leeduckgo** [comment]
> * ethereum-signer
> 
> 运行如图: ![image](https://user-images.githubusercontent.com/974169/212352167-1552f262-c04c-43d9-99c0-4f089aa85500.png)
> 
> 项目地址: https://github.com/v1xingyue/scaffold-eth 其他提示： 如果 mac 下运行，建议修改 package.json 去掉 --openssl-legacy-provider 选项，否则 可能运行不起来。
> 
> * aptos-signer
> 
> 运行效果如图: <img alt="image" width="1677" src="https://user-images.githubusercontent.com/974169/212527037-23c48ccd-f1ed-43ce-929f-e40fa6bfb686.png">
> 
> 项目地址: https://github.com/v1xingyue/scaffold-move.git

意见1：项目规范命名——更名为`eth-signer`和`aptos-signer`
意见2：通过`gh-pages`或者 Vercel 等其它代码托管平台部署程序

**Comment by v1xingyue** [comment]
> * ethereum-signer
> 
> 运行如图: ![image](https://user-images.githubusercontent.com/974169/212352167-1552f262-c04c-43d9-99c0-4f089aa85500.png)
> 
> 项目地址: https://github.com/v1xingyue/eth-signer 其他提示： 如果 mac 下运行，建议修改 package.json 去掉 --openssl-legacy-provider 选项，否则 可能运行不起来。
> 
> * aptos-signer
> 
> 运行效果如图: <img alt="image" width="1677" src="https://user-images.githubusercontent.com/974169/212527037-23c48ccd-f1ed-43ce-929f-e40fa6bfb686.png">
> 
> 项目地址: https://github.com/v1xingyue/aptos-signer

Done

**Comment by v1xingyue** [comment]
> > * ethereum-signer
> > 
> > 运行如图: ![image](https://user-images.githubusercontent.com/974169/212352167-1552f262-c04c-43d9-99c0-4f089aa85500.png)
> > 项目地址: https://github.com/v1xingyue/scaffold-eth 其他提示： 如果 mac 下运行，建议修改 package.json 去掉 --openssl-legacy-provider 选项，否则 可能运行不起来。
> > 
> > * aptos-signer
> > 
> > 运行效果如图: <img alt="image" width="1677" src="https://user-images.githubusercontent.com/974169/212527037-23c48ccd-f1ed-43ce-929f-e40fa6bfb686.png">
> > 项目地址: https://github.com/v1xingyue/scaffold-move.git
> 
> 意见1：项目规范命名——更名为`eth-signer`和`aptos-signer` 意见2：通过`gh-pages`或者 Vercel 等其它代码托管平台部署程序

Done

**Comment by v1xingyue** [comment]
Done
