### ISSUE TITLE
feat: create a project for the show of all the issues of this org #1000R

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai-shang-projects#3]
Money: `1000R`

Comment below if you have any interest!

**Comment by qiwihui** [comment]
I am interested. :-)

**Comment by leeduckgo** [comment]
Great!

**Comment by qiwihui** [comment]
Features:
- display all issues in an org in one panel, supporting filtering and ordering.
- display all issues in a repo, support filtering and ordering.
- display all repos in an org.

deadline: March 10,2022

**Comment by qiwihui** [comment]
demo: https://qiwihui.github.io/github-issue-viewer/

**Comment by leeduckgo** [comment]
Great!
Allocated a domain for this:
> https://dao.noncegeek.com/
