### ISSUE TITLE
Buidl an Admin dApp based on Scaffold-Eth, for Web3DevNFT 

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai-shang-projects#4]
money: `800R`

Contract:
> https://moonbeam.moonscan.io/address/0xb6FC950C4bC9D1e4652CbEDaB748E8Cdcfe5655F

requirements:
- Home pages
- it's able to query the NFT by token id or the owner address
- Show all the Nfts minted(gallery)
- button to `add` and `remove` badges for an nft

```
  +---------+     +------------+    +----------+         
  |    add  |     |   remove   |    | confrim  |    /*badges preview*/
  +---------+     +------------+    +----------+
```

**Comment by zhangying-code** [comment]
🙋 在线等partner

**Comment by itherunder** [comment]
这里这里🙋🏻‍♀️

**Comment by leeduckgo** [comment]
Well Done!
> https://github.com/WeLightProject/Tai-Shang-DAO-NFT-Manager
