### ISSUE TITLE
[dApp] an dApp Based on scaffold-eth for meeting verify.

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai-shang-projects#9]
Money: `800R`
Deadline: `04.15`
Proj Name: `Tai-Shang-Meeting-Verifier`
Requirements:
- no need for any contract now.
Homepage:
- Check if the user's addr in whitelist with backend
   - if in the whitelist, show the meeting infomations provided by backend
   - if not in the whitelist, show a link to the apply document provided by the backend
- Impl a simple backend, you can write it with Python or Elixir.

Reference:
> https://github.com/WeLightProject/Tai-Shang-Voxel-Handler

**Comment by wartstone** [comment]
i would try if no one takes it yet

**Comment by itherunder** [comment]
here🙋🏻‍♂️

**Comment by leeduckgo** [comment]
https://github.com/itherunder/Tai-Shang-Meeting-Verifier
